export enum EventTypes {
  PatientSummary = 'Patient Summary',
  HR = 'HR',
  BP = 'BP',
  Sats = 'Sats',
  Temp = 'Temp',
  RR = 'RR',
  BG = 'BG',
  Examination = 'Examination',
  Complaint = 'Complaint',
  Treatment = 'Treatment',
  Diagnosis = 'Diagnosis',
  MedicineDispensed = 'Medicine Dispensed',
  Prescriptions = 'Prescriptions',
  Allergies = 'Allergies',
  MedicalHistory = 'Medical History',
  Camp = 'Camp',
  Notes = 'Notes',
  Covid19Screening = 'COVID-19 Screening'
}