export enum EventTypes {
  PatientSummary = 'Patient Summary',
  Camp = 'Camp',
  VisitType = 'Visit Type',
  Vitals = 'Vitals',
  Examination = 'Examination',
  ExaminationFull = 'Examination Full',
  Medicine = 'Medicine',
  Complaint = 'Complaint',
  Treatment = 'Treatment',
  Diagnosis = 'Diagnosis',
  MedicineDispensed = 'Medicine Dispensed',
  Prescriptions = 'Prescriptions',
  Allergies = 'Allergies',
  MedicalHistory = 'Medical History',
  MedicalHistoryFull = 'Medical History Full',
  Notes = 'Notes',
  Covid19Screening = 'COVID-19 Screening',
  DentalTreatment = 'Dental Treatment',
  Physiotherapy = 'Physiotherapy'
}