export const LocalizedStrings = {
  "en": {
    patients: "Patients",
    PATIENTS: "< PATIENTS",
    welcome: "Welcome Back",
    dob: "Date of Birth",
    DOB: "DOB",
    sex: "Sex",
    gender: "Gender",
    GENDER: "GENDER",
    patientSummary: "Patient Summary",
    noContent: "No content yet",
    age: "AGE",
    edit: "EDIT",
    back: "< BACK",
    save: "SAVE",
    confirm: "CONFIRM",
    cancel: "CANCEL",

    firstName: "First Name",
    surname: "Surname",
    country: "Country",
    hometown: "Hometown",
    selectDob: "Select DOB",
    phone: "Phone",

    camp: "Camp",
    vitals: "Vitals",
    examinationNotes: "Examination Notes",
    complaint: "Complaint",
    treatment: "Treatment",
    diagnosis: "Diagnosis",
    medicineDispensed: "Medicine Dispensed",
    prescriptions: "Prescriptions",
    allergies: "Allergies",
    medicalHistory: "Medical History",
    enterTextHere: "Enter text here.",
    visitDate: "Visit Date",
    visitHistory: "VISIT HISTORY",
    visitEvents: "Visit Events",
    trends: "TRENDS",
    eventType: "Event Type",
    provider: "Provider"
  },
  "ar": {
    patients: "المرضى",
    PATIENTS: "المرضى",
    welcome: "مرحبا بعودتك",
    dob: "تاريخ الولادة",
    DOB: "تاريخ الولادة",
    sex: "جنس",
    gender: "جنس",
    GENDER: "جنس",
    patientSummary: "ملخص المريض",
    noContent: "لا يوجد محتوى حتى الآن",
    age: "عمر",
    edit: "تعديل",
    back: "رجع",
    save: "حفظ",
    confirm: "تؤكد",
    cancel: "إلغاء",

    firstName: "الاسم المعطى",
    surname: "الكنية",
    country: "بلد",
    hometown: "مسقط رأس",
    selectDob: "اختر تاريخ الميلاد",
    phone: "هاتف",

    camp: "مخيم",
    vitals: "الأعضاء الحيوية",
    examinationNotes: "ملاحظات الفحص",
    complaint: "شكوى",
    treatment: "علاج او معاملة",
    diagnosis: "التشخيص",
    medicineDispensed: "الأدوية المستغلة",
    prescriptions: "وصفات",
    allergies: "الحساسية",
    medicalHistory: "تاريخ طبى",
    enterTextHere: "أدخل النص هنا",
    visitDate: "موعد زيارة",
    visitHistory: "زيارة التاريخ",
    visitEvents: "زيارة الأحداث",
    trends: "اتجاهات",
    eventType: "نوع الحدث",
    provider: "طبيب"
  }
};