export const LocalizedStrings = {
  "en": {
    patients: "Patients",
    PATIENTS: "< PATIENTS",
    welcome: "Welcome Back",
    dob: "Date of Birth",
    DOB: "DOB",
    sex: "Sex",
    gender: "Gender",
    GENDER: "GENDER",
    patientSummary: "Patient Summary",
    noContent: "No content yet",
    age: "AGE",
    edit: "EDIT",
    back: "< BACK",
    save: "SAVE",
    confirm: "CONFIRM",
    cancel: "CANCEL",
    yes: "Y",
    no: "N",
    firstName: "First Name",
    surname: "Surname",
    country: "Country",
    hometown: "Hometown",
    selectDob: "Select DOB",
    phone: "Phone",
    patientSearch: "Search patient name...",
    search: "Search",
    minAge: "Min Age",
    maxAge: "Max Age",
    advancedFilters: "Advanced Filters ▼",
    hideFilters: "Hide Filters",
    clearFilters: "Clear All Filters",
    newPatient: "New Patient",
    newVisit: "New Visit",
    newEntry: "New Entry",
    camp: "Camp",
    vitals: "Vitals",
    examination: "Examination",
    notes: "Notes",
    complaint: "Complaint",
    treatment: "Treatment",
    diagnosis: "Diagnosis",
    medicineDispensed: "Medicine Dispensed",
    prescriptions: "Prescriptions",
    allergies: "Allergies",
    medicalHistory: "Medical History",
    covidScreening: "COVID-19 Screening",
    enterTextHere: "Enter text here.",
    visitDate: "Visit Date",
    visitHistory: "Visit History",
    visitEvents: "Visit Events",
    visitType: "Visit Type",
    trends: "TRENDS",
    eventType: "Event Type",
    datePrescribed: "Date Prescibed",
    provider: "Provider",
    severity: "Severity",
    onsetDate: "Onset Date",
    departure: "Departure",
    to: "to",
    return: "Return",
    fever: "Fever or Chills?",
    dryCough: "Dry Cough?",
    diffBreathing: "Difficulty Breathing?",
    soreThroat: "Sore Throat or Runny Nose?",
    nausea: "Nausea, vomiting, or diarrhea?",
    chestPain: "Chest Pain?",
    confusion: "New Confusion?",
    bluish: "Bluish Lips or Face?",
    fatigue: "Fatigue?",
    aches: "Aches and Pains?",
    headache: "Headache?",
    changeTasteSmell: "Change of Taste or Smell?",
    diabetes: "Diabetes?",
    cardioDisease: "Cardiovascular Disease?",
    pulmonaryDisease: "Pulmonary Disease?",
    renalDisease: "Renal Disease?",
    malignancy: "Malignancy?",
    pregnant: "Pregnant or 2 weeks postpartum?",
    immunocompromised: "Immunocompromised?",
    exposureKnown: "Recent contact with individuals with known or suspected COVID-19?",
    travel: "Recent travel out of the country?",
    symptomsDate: "Onset Date of first symptoms?",
    riskFactors: "Risk Factors",
    hideRiskFactors: "Hide Risk Factors",
    testIsolate: "Test/Isolate Patient",
    seekCare: "Seek Emergency Care and Isolate",
    noAction: "No Action Necessary",
    syncFailure: "Database Sync Failure!",
    syncFailureConnection: "Check internet connection",
    syncFailureSystem: "Contact system administrator",
    syncSuccess: "Database Sync Success",
    surgeryHx: "Previous Surgeries",
    chronicConditions: "Chronic Conditions",
    currentMedications: "Current Medications",
    vaccinations: "Vaccinations",
    generalObservations: "General Observations",
    covid19: "COVID-19",
    referral: "Referral to Specialist",
    medicine: "Medicine",
    medication: "Medication",
    type: "Type",
    tablet: "Tablet",
    syrup: "Syrup",
    ampule: "Ampule",
    suppository: "Suppository",
    cream: "Cream",
    drops: "Drops",
    bottle: "Bottle",
    spray: "Spray",
    gel: "Gel",
    lotion: "Lotion",
    dosage: "Dosage",
    days: "Days",
    dentalTreatment: "Dental Treatment",
    physiotherapy: "Physiotherapy",
    previousTreatment: "Previous Physio Treatment",
    findings: "Examination Findings",
    treatmentPlan: "Treatment Plan",
    treatmentSession: "Treatment Session",
    recommendations: "Recommendations",
    patientSnapshot: "Patient Snapshot",
  },
  "ar": {
    patients: "المرضى",
    PATIENTS: "المرضى",
    welcome: "مرحبا بعودتك",
    dob: "تاريخ الولادة",
    DOB: "تاريخ الولادة",
    sex: "جنس",
    gender: "جنس",
    GENDER: "جنس",
    patientSummary: "ملخص المريض",
    noContent: "لا يوجد محتوى حتى الآن",
    age: "عمر",
    edit: "تعديل",
    back: "رجع",
    save: "حفظ",
    confirm: "تؤكد",
    cancel: "إلغاء",
    yes: "نعم",
    no: "لا",
    firstName: "الاسم المعطى",
    surname: "الكنية",
    country: "بلد",
    hometown: "مسقط رأس",
    selectDob: "اختر تاريخ الميلاد",
    phone: "هاتف",
    patientSearch: "البحث عن اسم المريض",
    search: "بحث",
    minAge: "الحد الإدنى للعمر",
    maxAge: "العمر الأقصى",
    advancedFilters: "مرشحات متقدمة ▼",
    hideFilters: "إخفاء المرشحات",
    clearFilters: "إعادة تعيين الفلاتر",
    newPatient: "مريض جديد",
    newVisit: "زيارة جديدة",
    newEntry: "دخول جديد",
    camp: "مخيم",
    vitals: "الأعضاء الحيوية",
    examination: "فحص",
    notes: "ملاحظات",
    complaint: "شكوى",
    treatment: "علاج او معاملة",
    diagnosis: "التشخيص",
    medicineDispensed: "الأدوية المستغلة",
    prescriptions: "وصفات",
    allergies: "الحساسية",
    medicalHistory: "تاريخ طبى",
    covidScreening: "COVID-19 فحص",
    enterTextHere: "أدخل النص هنا",
    visitDate: "موعد زيارة",
    visitHistory: "زيارة التاريخ",
    visitEvents: "زيارة الأحداث",
    visitType: "نوع الزيارة",
    trends: "اتجاهات",
    eventType: "نوع الحدث",
    datePrescribed: "التاريخ المحدد",
    provider: "طبيب",
    severity: "خطورة",
    onsetDate: "تاريخ البداية",
    departure: "مغادرة",
    to: "إلى",
    return: "إرجاع",
    fever: "حمى أم قشعريرة؟",
    dryCough: "سعال جاف؟",
    diffBreathing: "صعوبة في التنفس؟",
    soreThroat: "التهاب بالحلق أو سيلان  بالأنف؟",
    nausea: "غثيان، قيء، او إسهال؟",
    chestPain: "ألم في الصدر؟",
    confusion: "اضطراب إدراكي حديث؟",
    bluish: "الشفاه الزرقاء أم الوجه؟",
    fatigue: "إعياء؟",
    aches: "اوجاع والآم؟",
    headache: "صداع الراس؟",
    changeTasteSmell: "تغير في الطعم أو الرائحة؟",
    diabetes: "داء السكري؟",
    cardioDisease: "أمراض القلب والأوعية الدموية؟",
    pulmonaryDisease: "المرض الرئوي؟",
    renalDisease: "امراض الكلى؟",
    malignancy: "خباثة؟",
    pregnant: "حامل أو أسبوعين بعد الولادة؟",
    immunocompromised: "المنقوصي المناعة؟",
    exposureKnown: "مخالطة أفراد مصابين او مشتبهين بالإصابة بفيروس كوفيد-١٩؟",
    travel: "السفر خارج البلاد بالآونة الأخيرة؟",
    symptomsDate: "تاريخ ظهور الأعراض الأولى؟",
    riskFactors: "عوامل الخطر",
    hideRiskFactors: "إخفاء عوامل الخطر",
    testIsolate: "اختبار وعزل المريض",
    seekCare: "احصل على رعاية الطوارئ واعزل نفسك",
    noAction: "لا رد فعل",
    syncFailure: "فشل مزامنة قاعدة البيانات",
    syncFailureConnection: "تحقق من اتصال الإنترنت",
    syncFailureSystem: "اتصل بمسؤول النظام",
    syncSuccess: "نجاح مزامنة قاعدة البيانات",
    surgeryHx: "العمليات السابقة",
    chronicConditions: "الامراض المزمنة",
    currentMedications: "الأدوية الحالية",
    vaccinations: "التطعيمات ",
    generalObservations: "مراقبة عامة",
    covid19: "كوفيد-١٩",
    referral: "تحويل الى مختص",
    medicine: "طب",
    medication: "دواء",
    type: "نوع",
    tablet: "قرص",
    syrup: "شراب",
    ampule: "امبولة",
    suppository: "تحميلة",
    cream: "مرهم",
    drops: "قطرات",
    bottle: "زجاجة",
    spray: "رذاذ",
    gel: "جل",
    lotion: "غسول",
    dosage: "جرعة",
    days: "ايام",
    dentalTreatment: "العناية بالاسنان",
    physiotherapy: "العلاج الطبيعي",
    previousTreatment: "جلسات العلاج الطبيعي السابقة",
    findings: "نتائج الفحص",
    treatmentPlan: "خطة العلاج ",
    treatmentSession: "جلسة العلاج",
    recommendations: "توصيات",
    patientSnapshot: "صفحة المريض",
  },
  "sp": {
    patients: "Pacientes",
    PATIENTS: "PACIENTES",
    welcome: "Bienvenido de vuelta",
    dob: "Fecha de nacimiento ",
    DOB: "Fecha de nacimiento ",
    sex: "Sexo",
    gender: "Género",
    GENDER: "GENERO",
    patientSummary: "Resumen del paciente",
    noContent: "No hay contenido aún",
    age: "EDAD",
    edit: "EDITAR",
    back: "< Volver a atrás",
    save: "GUARDAR",
    confirm: "CONFIRMAR",
    cancel: "CANCELAR",
    yes: "Sí",
    no: "No",
    firstName: "Nombre",
    surname: "Apellido",
    country: "País",
    hometown: "Ciudad de origen",
    selectDob: "Seleccione fecha de nacimiento",
    phone: "Teléfono",
    patientSearch: "Buscar nombre del paciente...",
    search: "Buscar",
    minAge: "Edad Mínima",
    maxAge: "Edad Máxima",
    advancedFilters: "Filtros Avanzados ▼",
    hideFilters: "Ocultar Filtros",
    clearFilters: "Restablecer Filtros",
    camp: "Nombre del campo de refugiados",
    vitals: "Signos vitales",
    examination: "Examen físico",
    notes: "Notas",
    complaint: "Queja/Preocupación médica",
    treatment: "Tratamiento",
    diagnosis: "Diagnóstico",
    medicineDispensed: "Medicamento suscrito",
    prescriptions: "Recetas de medicamentos",
    allergies: "Alergias",
    medicalHistory: "Historial médico",
    covidScreening: "Prueba de COVID-19",
    enterTextHere: "Introduzca texto aquí",
    visitDate: "Fecha de la visita",
    visitHistory: "Historia de la visita",
    visitEvents: "Eventos durante la visita",
    visitType: "Tipo de visita",
    trends: "Tendencias",
    eventType: "Tipo de evento",
    datePrescribed: "Fecha de prescripción",
    provider: "Proveedor médico",
    severity: "Severidad",
    onsetDate: "Fecha de comienzo de los síntomas",
    departure: "Ida",
    to: "a ",
    return: "Vuelta",
    fever: "¿Fiebre o escalofríos?",
    dryCough: "¿Tos seca?",
    diffBreathing: "¿Dificultad al respirar?",
    soreThroat: "¿Dolor de garganta o secreción nasal?",
    nausea: "¿Náuseas, vómitos o diarrea?",
    chestPain: "¿Dolor de pecho?",
    confusion: "¿Nueva confusión?",
    bluish: "¿Labios azulados/ violetas?",
    fatigue: "¿Fatiga?",
    aches: "¿Dolores y molestias?",
    headache: "¿Dolor de cabeza?",
    changeTasteSmell: "¿Cambio de gusto u olfato?",
    diabetes: "¿Diabetes?",
    cardioDisease: "¿Problemas del corazón?",
    pulmonaryDisease: "¿Enfermedad en los pulmones?",
    renalDisease: "¿Enfermedad de los riñones?",
    malignancy: "¿Cáncer?",
    pregnant: "¿Mujer recién dada a luz?",
    immunocompromised: "¿Inmunocomprometido? / ¿Tiene las defensas bajas?",
    exposureKnown: "¿Contacto reciente con personas con COVID-19 conocido o sospechado?",
    travel: "¿Viaje reciente fuera del país?",
    symptomsDate: "¿Fecha de aparición de los primeros síntomas?",
    riskFactors: "Factores de riesgo",
    hideRiskFactors: "Ocultar factores de riesgo",
    testIsolate: "Hacerle la prueba/Aislar al paciente",
    seekCare: "Busque atención de emergencia y aísle",
    noAction: "No es necesario tomar ninguna acción",
    syncFailure: "¡Fallo de sincronización!",
    syncFailureConnection: "Verifica la conexión a internet",
    syncFailureSystem: "Comuníquese con el administrador del sistema",
    syncSuccess: "Éxito en la sincronización",
  }
};