export const NameVariants = [
  ['muhammad', 'mohammed', 'mohammad', 'muhammed', 'mohamed', 'mohamad', 'muhamad', 'muhamed', 'mohamud', 'mohummad', 'mohummed', 'mouhamed', 'mohammod', 'mouhamad', 'mohamod'],
  ['khadijah', 'kadijah', 'kadija', 'khedijah', 'khedijeh', 'khadijeh', 'kedija', 'khedije', 'khadije', 'khadeejah', 'kadeejah', 'kadeeja'],
  ['leila', 'layla', 'leyla', 'laila', 'leilah', 'laylah', 'leylah', 'lailah'],
  ['ayesha', 'aiesha', 'aisha', 'aishah', 'aisheh', 'aishe', 'ayshe', 'aysha'],
  ['ameena', 'amina', 'amna', 'amena', 'ameenah', 'aminah', 'amnah', 'amenah'],
  ['mariam', 'mariam', 'maryem', 'meriam', 'meryam', 'meryem', 'miryam', 'miriam'],
  ['abdurrahman', 'abdur rahman', 'abdul rahman', 'abdurahman', 'abdorrahman', 'abdorahman', 'abdor rahman'],
  ['hussein', 'hussain', 'husein', 'husain', 'husyan'],
  ['abdullah', 'abdallah', 'abdellah', 'abdulah'],
  ['ahmad', 'ahmed', 'akhmed', 'akhmad'],
  ['karim', 'kareem', 'careem', 'carim'],
  ['zehra', 'zehra', 'zahraa'],
  ['Fatima', 'Fatma', 'Fatema'],
  ['mahmoud', 'mahmud', 'mahmood'],
  ['mona', 'muna', 'moona'],
  ['omar', 'umar'],
  ['hassan', 'hasan'],
]